Repository databricks/terraform-provider-databricks, pull requests merged in 2023-05, with the labels that each got.

#2251 Added support for running `databricks_cluster` init scripts from workspace files
  clusters/clusters_api.go
  docs/resources/cluster.md
Labels: ready-to-merge

#2258 Exporter: relax handling of problematic files/directories
  exporter/context.go
  exporter/exporter_test.go
  exporter/importables.go
  exporter/util.go
  workspace/data_notebook_paths.go
  workspace/resource_notebook.go
  workspace/resource_notebook_test.go
Labels: ready-to-merge

#2284 Fix TestAccWorkspaceFileBase64
  internal/acceptance/workspace_file_test.go
Labels: ready-to-merge

#2242 Clarifying about tag propagation and tag conflict for `databricks_instance_pool` resource
  docs/resources/instance_pool.md
Labels: docs, ready-to-merge

#2290 Removed reference to deprecated `databricks_group_instance_profile` from `databricks_group_role` docs
  docs/resources/group_role.md
Labels: ready-to-merge

#2285 Fix dependency when exporting `databricks_service_principal_role`
  exporter/importables.go
Labels: ready-to-merge

#2322 (#2319) Update `edition` and `channel` values in docs.
  docs/resources/pipeline.md
Labels: docs

#2298 Automatically add `CAN_MANAGE` permission on `databricks_instance_pool` to calling user
  permissions/resource_permissions.go
Labels: ready-to-merge

#2336 Add suppress diff for URL change that only change `/` (remove or add) in UC resources
  catalog/resource_catalog.go
  catalog/resource_catalog_test.go
  catalog/resource_external_location.go
  catalog/resource_schema.go
Labels: ready-to-merge

#2332 Document fix for `databricks_service_principal_secret`
  docs/index.md
  docs/resources/service_principal_secret.md
Labels: ready-to-merge
